name: Automatic Tag Generation with autotag

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  create-tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pantheon-systems/action-autotag@v0
        with:
          scheme: conventional
          gh-token: ${{ github.token }}

