name: Automatic Tag Generation with autotag

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'

permissions:
  contents: write

jobs:
  create-tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oobook/automated-tag@v0.3.0
        with:
          gh-token: ${{ github.token }}

