name: "Release Tag"

# Run on every commit tag which begins with 'v' except BREAKING Change
on:
  push:
    branches:
      - maintenance
    # tags:
    #   - 'v[0-9]+\.[0-9]+\.[0-9]+\-rc'

jobs:
  release:
    name: "Release the tag"
    runs-on: "ubuntu-latest"
    steps:
      - name: Run Workflow (if not BREAKING CHANGE)
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
