name: "Release Tag"

# Run on every commit tag which begins with 'v' except BREAKING Change
on:
  push:
    tags:
      - 'v(\d+)\.(?!0\.0$)(\d+)\.(\d+)'
      # - 'v[0-9]+\.[0-9]+\.[0-9]+'
      # - "v*"


# Automatically create a Github Release, with release details specified (the relevant commits)
jobs:
  release:
    name: "Release the tag"
    runs-on: "ubuntu-latest"
    steps:
      - name: Run Workflow (if not BREAKING CHANGE)
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
