name: Release

on:
  push:
    branches:
      - _main
    tags-ignore:
      - v*
    paths-ignore:
      - '**.md'
      - '**.yml'

permissions:
  contents: write

jobs:
  create-tag-prerelease:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oobook/automated-tag@v1
        id: tag-generation
        with:
          gh_token: ${{ github.token }}
      - name: Create Release
        uses: oobook/automated-release@v1
        id: release-generation
        with:
          gh_token: ${{ secrets.GITHUB_TOKEN }}
          tag: "${{ steps.tag-generation.outputs.tag }}"
          prerelease: true
