name: "Release"

# Run on every commit tag which begins with 'v' except BREAKING Change
on:
  push:
    # branches:
    #   - maintenance
    tags:
      - 'v*'
    # paths-ignore:
    #   - '**.md'
    #   - '**.yml'

# Automatically create a Github Release, with release details specified (the relevant commits)
jobs:
  release:
    name: "Release the new version from the related tag"
    runs-on: "ubuntu-latest"
    steps:
      - name: Run Workflow (if not BREAKING CHANGE)
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
